//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimitlessBeautySalon.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LimitlessBeautySalon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _10 {
            get {
                object obj = ResourceManager.GetObject("10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _12 {
            get {
                object obj = ResourceManager.GetObject("12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _136488 {
            get {
                object obj = ResourceManager.GetObject("136488", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1364881 {
            get {
                object obj = ResourceManager.GetObject("1364881", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _492345 {
            get {
                object obj = ResourceManager.GetObject("492345", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9a7d82e52c3095a7f7cb2b7ff13e92d3 {
            get {
                object obj = ResourceManager.GetObject("9a7d82e52c3095a7f7cb2b7ff13e92d3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap abstract_golden_glowing_wave_banner {
            get {
                object obj = ResourceManager.GetObject("abstract-golden-glowing-wave-banner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap abstract_golden_glowing_wave_banner1 {
            get {
                object obj = ResourceManager.GetObject("abstract-golden-glowing-wave-banner1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap abstract_premium_black_gold_geometric_background_1017_24783 {
            get {
                object obj = ResourceManager.GetObject("abstract-premium-black-gold-geometric-background_1017-24783", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap abstract_premium_black_gold_geometric_background_1017_247831 {
            get {
                object obj = ResourceManager.GetObject("abstract-premium-black-gold-geometric-background_1017-247831", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bigstock_Abstract_Stylish_Light_Effect_227173600_1024x640 {
            get {
                object obj = ResourceManager.GetObject("bigstock-Abstract-Stylish-Light-Effect-227173600-1024x640", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download {
            get {
                object obj = ResourceManager.GetObject("download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap free_strass_vector_gold_glitter_texture_on_black_background {
            get {
                object obj = ResourceManager.GetObject("free-strass-vector-gold-glitter-texture-on-black-background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap free_strass_vector_gold_glitter_texture_on_black_background1 {
            get {
                object obj = ResourceManager.GetObject("free-strass-vector-gold-glitter-texture-on-black-background1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_bl_1649_Browser_web_internet_magnifier_search_engine_4575068 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_bl_1649_Browser_web_internet_magnifier_search_engine_4575068", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_Rounded_10_2024633 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_Rounded-10_2024633", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images {
            get {
                object obj = ResourceManager.GetObject("images", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap magnifier {
            get {
                object obj = ResourceManager.GetObject("magnifier", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_abstract_metallic_black_gold_frame_sport_design_concept_innovation_background_image_305000 {
            get {
                object obj = ResourceManager.GetObject("pngtree-abstract-metallic-black-gold-frame-sport-design-concept-innovation-backgr" +
                        "ound-image_305000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_abstract_metallic_black_gold_frame_sport_design_concept_innovation_background_image_3050001 {
            get {
                object obj = ResourceManager.GetObject("pngtree-abstract-metallic-black-gold-frame-sport-design-concept-innovation-backgr" +
                        "ound-image_3050001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_atmosphere_gold_powder_background_black_gold_golden_particle_image_22326 {
            get {
                object obj = ResourceManager.GetObject("pngtree-atmosphere-gold-powder-background-black-gold-golden-particle-image_22326", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_black_atmospheric_financial_technology_conference_background_image_145942 {
            get {
                object obj = ResourceManager.GetObject("pngtree-black-atmospheric-financial-technology-conference-background-image_145942" +
                        "", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_black_gold_background_golden_streamer_commendation_assembly_background_material_goldgolden_streameraward_image_73706 {
            get {
                object obj = ResourceManager.GetObject("pngtree-black-gold-background-golden-streamer-commendation-assembly-background-ma" +
                        "terial-goldgolden-streameraward-image_73706", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_black_gold_light_effect_atmosphere_creative_image_16647 {
            get {
                object obj = ResourceManager.GetObject("pngtree-black-gold-light-effect-atmosphere-creative-image_16647", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_black_gold_light_effect_atmosphere_creative_image_166471 {
            get {
                object obj = ResourceManager.GetObject("pngtree-black-gold-light-effect-atmosphere-creative-image_166471", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_black_gold_real_estate_financial_background_map_image_190153 {
            get {
                object obj = ResourceManager.GetObject("pngtree-black-gold-real-estate-financial-background-map-image_190153", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_domineering_black_gold_new_year_party_background_material_gold_windgolden_stream_image_71401 {
            get {
                object obj = ResourceManager.GetObject("pngtree-domineering-black-gold-new-year-party-background-material-gold-windgolden" +
                        "-stream-image_71401", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_gold_glitter_texture_isolated_on_black_background_image_308336 {
            get {
                object obj = ResourceManager.GetObject("pngtree-gold-glitter-texture-isolated-on-black-background-image_308336", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_golden_black_atmosphere_high_end_vouchers_image_262051 {
            get {
                object obj = ResourceManager.GetObject("pngtree-golden-black-atmosphere-high-end-vouchers-image_262051", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_simple_black_gold_universal_background_material_goldlight_spotgeneral_backgroundbanner_image_83780 {
            get {
                object obj = ResourceManager.GetObject("pngtree-simple-black-gold-universal-background-material-goldlight-spotgeneral-bac" +
                        "kgroundbanner-image_83780", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
